I have done a few things here:
1) I have basic block solves with BelosLOWS[F] working now from MOOCHO.  I have yet to do some studies of this but so far it looks pretty good.

2) I removed the implicit conversions between Teuchos::Range1D and RangePack::Range1D.  This caused a bug that took me a long time to figure out.  Now you have to use convert(...) functions so this is more explicit now.

3) I got PL to read and write to XML files.  This needs to be made more general.

4) Other changes that I don't remember ...

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -274,7 +274,7 @@ PACKAGE_STRING='moocho version of the day'
 PACKAGE_BUGREPORT='rabartl@sandia.gov'
 
 ac_unique_file="/src/MoochoUtilities/src/SpecialASCII.hpp"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP ENABLE_MOOCHO_MA28_TRUE ENABLE_MOOCHO_MA28_FALSE ENABLE_MOOCHO_THYRA_TRUE ENABLE_MOOCHO_THYRA_FALSE ENABLE_EPETRAEXT_THYRA_TRUE ENABLE_EPETRAEXT_THYRA_FALSE ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE FLIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP ENABLE_MOOCHO_MA28_TRUE ENABLE_MOOCHO_MA28_FALSE ENABLE_MOOCHO_THYRA_TRUE ENABLE_MOOCHO_THYRA_FALSE ENABLE_EPETRAEXT_THYRA_TRUE ENABLE_EPETRAEXT_THYRA_FALSE ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE ENABLE_AZTECOO_THYRA_TRUE ENABLE_AZTECOO_THYRA_FALSE ENABLE_BELOS_THYRA_TRUE ENABLE_BELOS_THYRA_FALSE ENABLE_IFPACK_THYRA_TRUE ENABLE_IFPACK_THYRA_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE FLIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -849,6 +849,12 @@ Optional Features:
                           See epetraext/configure --help
   --enable-thyra          See amesos/configure --help
   --enable-amesos-thyra   See amesos/configure --help
+  --enable-thyra          See aztecoo/configure --help
+  --enable-aztecoo-thyra  See aztecoo/configure --help
+  --enable-thyra          See belos/configure --help
+  --enable-belos-thyra    See belos/configure --help
+  --enable-thyra          See ifpack/configure --help
+  --enable-ifpack-thyra   See ifpack/configure --help
   --enable-tests          Build tests for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
                           yes)
@@ -3787,7 +3793,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3790:" \
+echo "$as_me:3796:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4915,6 +4921,165 @@ fi
 
 
 
+
+
+# Check whether --enable-thyra or --disable-thyra was given.
+if test "${enable_thyra+set}" = set; then
+  enableval="$enable_thyra"
+  ac_cv_implicit_use_thyra=$enableval
+else
+  ac_cv_implicit_use_thyra=no
+fi;
+
+if test "Xyes" != "Xno"; then
+  ac_cv_aztecoo_using_thyra_default=$ac_cv_implicit_use_thyra
+else
+  ac_cv_aztecoo_using_thyra_default=no
+fi
+
+# Check whether --enable-aztecoo-thyra or --disable-aztecoo-thyra was given.
+if test "${enable_aztecoo_thyra+set}" = set; then
+  enableval="$enable_aztecoo_thyra"
+  ac_cv_use_thyra=$enableval
+else
+  ac_cv_use_thyra=$ac_cv_aztecoo_using_thyra_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional thyra dependent code in aztecoo" >&5
+echo $ECHO_N "checking whether to build optional thyra dependent code in aztecoo... $ECHO_C" >&6
+
+if test "X$ac_cv_use_thyra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AZTECOO_THYRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_thyra" = "Xyes"; then
+  ENABLE_AZTECOO_THYRA_TRUE=
+  ENABLE_AZTECOO_THYRA_FALSE='#'
+else
+  ENABLE_AZTECOO_THYRA_TRUE='#'
+  ENABLE_AZTECOO_THYRA_FALSE=
+fi
+
+
+
+
+
+
+# Check whether --enable-thyra or --disable-thyra was given.
+if test "${enable_thyra+set}" = set; then
+  enableval="$enable_thyra"
+  ac_cv_implicit_use_thyra=$enableval
+else
+  ac_cv_implicit_use_thyra=no
+fi;
+
+if test "Xyes" != "Xno"; then
+  ac_cv_belos_using_thyra_default=$ac_cv_implicit_use_thyra
+else
+  ac_cv_belos_using_thyra_default=no
+fi
+
+# Check whether --enable-belos-thyra or --disable-belos-thyra was given.
+if test "${enable_belos_thyra+set}" = set; then
+  enableval="$enable_belos_thyra"
+  ac_cv_use_thyra=$enableval
+else
+  ac_cv_use_thyra=$ac_cv_belos_using_thyra_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional thyra dependent code in belos" >&5
+echo $ECHO_N "checking whether to build optional thyra dependent code in belos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_thyra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BELOS_THYRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_thyra" = "Xyes"; then
+  ENABLE_BELOS_THYRA_TRUE=
+  ENABLE_BELOS_THYRA_FALSE='#'
+else
+  ENABLE_BELOS_THYRA_TRUE='#'
+  ENABLE_BELOS_THYRA_FALSE=
+fi
+
+
+
+
+
+
+# Check whether --enable-thyra or --disable-thyra was given.
+if test "${enable_thyra+set}" = set; then
+  enableval="$enable_thyra"
+  ac_cv_implicit_use_thyra=$enableval
+else
+  ac_cv_implicit_use_thyra=no
+fi;
+
+if test "Xyes" != "Xno"; then
+  ac_cv_ifpack_using_thyra_default=$ac_cv_implicit_use_thyra
+else
+  ac_cv_ifpack_using_thyra_default=no
+fi
+
+# Check whether --enable-ifpack-thyra or --disable-ifpack-thyra was given.
+if test "${enable_ifpack_thyra+set}" = set; then
+  enableval="$enable_ifpack_thyra"
+  ac_cv_use_thyra=$enableval
+else
+  ac_cv_use_thyra=$ac_cv_ifpack_using_thyra_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional thyra dependent code in ifpack" >&5
+echo $ECHO_N "checking whether to build optional thyra dependent code in ifpack... $ECHO_C" >&6
+
+if test "X$ac_cv_use_thyra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IFPACK_THYRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_thyra" = "Xyes"; then
+  ENABLE_IFPACK_THYRA_TRUE=
+  ENABLE_IFPACK_THYRA_FALSE='#'
+else
+  ENABLE_IFPACK_THYRA_TRUE='#'
+  ENABLE_IFPACK_THYRA_FALSE=
+fi
+
+
+
+
 # ------------------------------------------------------------------------
 # Checks if examples should be built
 # ------------------------------------------------------------------------
@@ -5643,7 +5808,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5646: \"$ac_link\") >&5
+(eval echo $as_me:5811: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5721,7 +5886,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5724: \"$ac_link\") >&5
+(eval echo $as_me:5889: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6111,6 +6276,27 @@ if test -z "${ENABLE_AMESOS_THYRA_TRUE}" && test -z "${ENABLE_AMESOS_THYRA_FALSE
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_AMESOS_THYRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_AMESOS_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_AZTECOO_THYRA_TRUE}" && test -z "${ENABLE_AZTECOO_THYRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_AZTECOO_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_AZTECOO_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_BELOS_THYRA_TRUE}" && test -z "${ENABLE_BELOS_THYRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_BELOS_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_BELOS_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_IFPACK_THYRA_TRUE}" && test -z "${ENABLE_IFPACK_THYRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_IFPACK_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_IFPACK_THYRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6778,6 +6964,12 @@ s,@ENABLE_EPETRAEXT_THYRA_TRUE@,$ENABLE_EPETRAEXT_THYRA_TRUE,;t t
 s,@ENABLE_EPETRAEXT_THYRA_FALSE@,$ENABLE_EPETRAEXT_THYRA_FALSE,;t t
 s,@ENABLE_AMESOS_THYRA_TRUE@,$ENABLE_AMESOS_THYRA_TRUE,;t t
 s,@ENABLE_AMESOS_THYRA_FALSE@,$ENABLE_AMESOS_THYRA_FALSE,;t t
+s,@ENABLE_AZTECOO_THYRA_TRUE@,$ENABLE_AZTECOO_THYRA_TRUE,;t t
+s,@ENABLE_AZTECOO_THYRA_FALSE@,$ENABLE_AZTECOO_THYRA_FALSE,;t t
+s,@ENABLE_BELOS_THYRA_TRUE@,$ENABLE_BELOS_THYRA_TRUE,;t t
+s,@ENABLE_BELOS_THYRA_FALSE@,$ENABLE_BELOS_THYRA_FALSE,;t t
+s,@ENABLE_IFPACK_THYRA_TRUE@,$ENABLE_IFPACK_THYRA_TRUE,;t t
+s,@ENABLE_IFPACK_THYRA_FALSE@,$ENABLE_IFPACK_THYRA_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
