I tried adding support for MA28 but it did not seem to work.  However, all of the tests passed so I will go ahead and check this in.  I also tried to put in the correct conditional commpilation for the Epetra/Thyra based example but have not relaly tested it fully.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -274,7 +274,7 @@ PACKAGE_STRING='moocho version of the day'
 PACKAGE_BUGREPORT='rabartl@sandia.gov'
 
 ac_unique_file="/src/MoochoUtilities/src/SpecialASCII.hpp"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE FLIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP ENABLE_MOOCHO_MA28_TRUE ENABLE_MOOCHO_MA28_FALSE ENABLE_EPETRAEXT_THYRA_TRUE ENABLE_EPETRAEXT_THYRA_FALSE ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE FLIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -838,6 +838,18 @@ Optional Features:
   --enable-mpi            MPI support
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --enable-ma28           Build in support for HSL solver MA28 into Moocho.
+                          Can be overridden with --disable-moocho-ma28.
+  --enable-moocho-ma28    Build in support for HSL solver MA28 into Moocho.
+  --enable-thyra          Build the Thyra adapater support in EpetraExt. Can
+                          be overridden with --disable-epetraext-thyra.
+  --enable-epetraext-thyra
+                          Build the Thyra adapater support in EpetraExt.
+  --enable-thyra          Build the Thyra operator/vector adapater support in
+                          Amesos. Can be overridden with
+                          --disable-amesos-thyra.
+  --enable-amesos-thyra   Build the Thyra operator/vector adapater support in
+                          Amesos.
   --enable-tests          Build tests for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
                           yes)
@@ -3776,7 +3788,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3779:" \
+echo "$as_me:3791:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4690,6 +4702,166 @@ esac
 # Checks for special package flags
 # ------------------------------------------------------------------------
 
+
+
+# Check whether --enable-ma28 or --disable-ma28 was given.
+if test "${enable_ma28+set}" = set; then
+  enableval="$enable_ma28"
+  ac_cv_implicit_use_ma28=$enableval
+else
+  ac_cv_implicit_use_ma28=no
+fi;
+
+if test "Xyes" != "Xno"; then
+  ac_cv_moocho_using_ma28_default=$ac_cv_implicit_use_ma28
+else
+  ac_cv_moocho_using_ma28_default=no
+fi
+
+# Check whether --enable-moocho-ma28 or --disable-moocho-ma28 was given.
+if test "${enable_moocho_ma28+set}" = set; then
+  enableval="$enable_moocho_ma28"
+  ac_cv_use_ma28=$enableval
+else
+  ac_cv_use_ma28=$ac_cv_moocho_using_ma28_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional ma28 dependent code in moocho" >&5
+echo $ECHO_N "checking whether to build optional ma28 dependent code in moocho... $ECHO_C" >&6
+
+if test "X$ac_cv_use_ma28" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MOOCHO_MA28 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_ma28" = "Xyes"; then
+  ENABLE_MOOCHO_MA28_TRUE=
+  ENABLE_MOOCHO_MA28_FALSE='#'
+else
+  ENABLE_MOOCHO_MA28_TRUE='#'
+  ENABLE_MOOCHO_MA28_FALSE=
+fi
+
+
+
+
+
+
+# Check whether --enable-thyra or --disable-thyra was given.
+if test "${enable_thyra+set}" = set; then
+  enableval="$enable_thyra"
+  ac_cv_implicit_use_thyra=$enableval
+else
+  ac_cv_implicit_use_thyra=no
+fi;
+
+if test "Xyes
+  " != "Xno"; then
+  ac_cv_epetraext_using_thyra_default=$ac_cv_implicit_use_thyra
+else
+  ac_cv_epetraext_using_thyra_default=no
+fi
+
+# Check whether --enable-epetraext-thyra or --disable-epetraext-thyra was given.
+if test "${enable_epetraext_thyra+set}" = set; then
+  enableval="$enable_epetraext_thyra"
+  ac_cv_use_thyra=$enableval
+else
+  ac_cv_use_thyra=$ac_cv_epetraext_using_thyra_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional thyra dependent code in epetraext" >&5
+echo $ECHO_N "checking whether to build optional thyra dependent code in epetraext... $ECHO_C" >&6
+
+if test "X$ac_cv_use_thyra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EPETRAEXT_THYRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_thyra" = "Xyes"; then
+  ENABLE_EPETRAEXT_THYRA_TRUE=
+  ENABLE_EPETRAEXT_THYRA_FALSE='#'
+else
+  ENABLE_EPETRAEXT_THYRA_TRUE='#'
+  ENABLE_EPETRAEXT_THYRA_FALSE=
+fi
+
+
+
+
+
+
+# Check whether --enable-thyra or --disable-thyra was given.
+if test "${enable_thyra+set}" = set; then
+  enableval="$enable_thyra"
+  ac_cv_implicit_use_thyra=$enableval
+else
+  ac_cv_implicit_use_thyra=no
+fi;
+
+if test "Xyes" != "Xno"; then
+  ac_cv_amesos_using_thyra_default=$ac_cv_implicit_use_thyra
+else
+  ac_cv_amesos_using_thyra_default=no
+fi
+
+# Check whether --enable-amesos-thyra or --disable-amesos-thyra was given.
+if test "${enable_amesos_thyra+set}" = set; then
+  enableval="$enable_amesos_thyra"
+  ac_cv_use_thyra=$enableval
+else
+  ac_cv_use_thyra=$ac_cv_amesos_using_thyra_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional thyra dependent code in amesos" >&5
+echo $ECHO_N "checking whether to build optional thyra dependent code in amesos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_thyra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMESOS_THYRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_thyra" = "Xyes"; then
+  ENABLE_AMESOS_THYRA_TRUE=
+  ENABLE_AMESOS_THYRA_FALSE='#'
+else
+  ENABLE_AMESOS_THYRA_TRUE='#'
+  ENABLE_AMESOS_THYRA_FALSE=
+fi
+
+
+
+
 # ------------------------------------------------------------------------
 # Checks if examples should be built
 # ------------------------------------------------------------------------
@@ -5418,7 +5590,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5421: \"$ac_link\") >&5
+(eval echo $as_me:5593: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5496,7 +5668,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5499: \"$ac_link\") >&5
+(eval echo $as_me:5671: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5667,7 +5839,6 @@ ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
 
 
 #  ----------------------------------------------------
@@ -5859,6 +6030,27 @@ if test -z "${USE_ALTERNATE_AR_TRUE}" && test -z "${USE_ALTERNATE_AR_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"USE_ALTERNATE_AR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_ALTERNATE_AR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_MOOCHO_MA28_TRUE}" && test -z "${ENABLE_MOOCHO_MA28_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_MOOCHO_MA28\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_MOOCHO_MA28\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_EPETRAEXT_THYRA_TRUE}" && test -z "${ENABLE_EPETRAEXT_THYRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_EPETRAEXT_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_EPETRAEXT_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_AMESOS_THYRA_TRUE}" && test -z "${ENABLE_AMESOS_THYRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_AMESOS_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_AMESOS_THYRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6514,6 +6706,12 @@ s,@USE_ALTERNATE_AR_TRUE@,$USE_ALTERNATE_AR_TRUE,;t t
 s,@USE_ALTERNATE_AR_FALSE@,$USE_ALTERNATE_AR_FALSE,;t t
 s,@ALTERNATE_AR@,$ALTERNATE_AR,;t t
 s,@CXXCPP@,$CXXCPP,;t t
+s,@ENABLE_MOOCHO_MA28_TRUE@,$ENABLE_MOOCHO_MA28_TRUE,;t t
+s,@ENABLE_MOOCHO_MA28_FALSE@,$ENABLE_MOOCHO_MA28_FALSE,;t t
+s,@ENABLE_EPETRAEXT_THYRA_TRUE@,$ENABLE_EPETRAEXT_THYRA_TRUE,;t t
+s,@ENABLE_EPETRAEXT_THYRA_FALSE@,$ENABLE_EPETRAEXT_THYRA_FALSE,;t t
+s,@ENABLE_AMESOS_THYRA_TRUE@,$ENABLE_AMESOS_THYRA_TRUE,;t t
+s,@ENABLE_AMESOS_THYRA_FALSE@,$ENABLE_AMESOS_THYRA_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
